"""
rl_env.py  —  P_RoboAI Studio

Gymnasium environments that wrap MuJoCo models generated by urdf_loader.

  MuJoCoArmEnv   — end-effector reaching task for robot arms
  MuJoCoAMREnv   — point-to-point navigation for differential-drive AMRs
"""
from __future__ import annotations

import math
from typing import Any

import mujoco
import numpy as np

try:
    import gymnasium as gym
    from gymnasium import spaces
    GYM_AVAILABLE = True
except ImportError:
    GYM_AVAILABLE = False


# ── Helpers ───────────────────────────────────────────────────────────────────

def _jnt_qpos(model: mujoco.MjModel, data: mujoco.MjData, name: str) -> float:
    jid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, name)
    if jid < 0:
        return 0.0
    return float(data.qpos[model.jnt_qposadr[jid]])


def _jnt_qvel(model: mujoco.MjModel, data: mujoco.MjData, name: str) -> float:
    jid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, name)
    if jid < 0:
        return 0.0
    return float(data.qvel[model.jnt_dofadr[jid]])


def _find_ee_body(model: mujoco.MjModel) -> int:
    """Return the body-id of the kinematic chain's leaf node (end-effector)."""
    has_children: set[int] = set()
    for i in range(model.nbody):
        p = model.body_parentid[i]
        if p != i:
            has_children.add(p)
    for i in range(model.nbody - 1, 0, -1):
        if i not in has_children:
            return i
    return model.nbody - 1


# ── ARM environment ───────────────────────────────────────────────────────────

class MuJoCoArmEnv:
    """
    End-effector reaching for a multi-joint arm.

    Observation (float32, shape = 2*n + 6):
        joint positions (n) · joint velocities (n) · ee_pos (3) · target (3)

    Action (float32, shape = n, range [-1, 1]):
        Normalised joint-position targets mapped to each joint's limit range.

    Reward:
        -dist_to_target  +  2.0 bonus when dist < 0.05 m
    """

    def __init__(self, mjcf_xml: str, joint_infos, max_steps: int = 200,
                 render_mode=None):
        if not GYM_AVAILABLE:
            raise ImportError("gymnasium is required for RL — pip install gymnasium")

        self._xml       = mjcf_xml
        self._ji        = [j for j in joint_infos if not j.is_wheel]
        self._max_steps = max_steps
        self._step_n    = 0
        self._target    = np.zeros(3, np.float32)

        self._model = mujoco.MjModel.from_xml_string(mjcf_xml)
        self._data  = mujoco.MjData(self._model)
        self._ee_id = _find_ee_body(self._model)

        # -- Target body for visualisation (injected into MJCF by urdf_loader) --
        self._target_bid = mujoco.mj_name2id(
            self._model, mujoco.mjtObj.mjOBJ_BODY, "rl_target")

        n = len(self._ji)
        high = np.inf * np.ones(2 * n + 6, np.float32)
        self.observation_space = spaces.Box(-high, high, dtype=np.float32)
        self.action_space      = spaces.Box(-1.0, 1.0, (n,), np.float32)
        self.render_mode       = render_mode

    # ── internals ─────────────────────────────────────────────────────────────

    def _obs(self) -> np.ndarray:
        pos = np.array([_jnt_qpos(self._model, self._data, j.name)
                        for j in self._ji], np.float32)
        vel = np.array([_jnt_qvel(self._model, self._data, j.name)
                        for j in self._ji], np.float32)
        ee  = self._data.xpos[self._ee_id].astype(np.float32)
        return np.concatenate([pos, vel, ee, self._target])

    def _sample_target(self) -> np.ndarray:
        r     = np.random.uniform(0.20, 0.45)
        theta = np.random.uniform(0.0, 2 * math.pi)
        z     = np.random.uniform(0.20, 0.65)
        return np.array([r * math.cos(theta), r * math.sin(theta), z], np.float32)

    def _move_target_marker(self) -> None:
        if self._target_bid < 0:
            return
        # Find the freejoint attached to rl_target body
        for jid in range(self._model.njnt):
            if self._model.jnt_bodyid[jid] == self._target_bid:
                qadr = self._model.jnt_qposadr[jid]
                self._data.qpos[qadr:qadr + 3] = self._target
                break

    # ── Gymnasium API ─────────────────────────────────────────────────────────

    def reset(self, *, seed=None, options=None):
        if seed is not None:
            np.random.seed(seed)
        mujoco.mj_resetData(self._model, self._data)
        for ji in self._ji:
            lo = max(ji.lower, -1.5) if not math.isinf(ji.lower) else -1.5
            hi = min(ji.upper,  1.5) if not math.isinf(ji.upper) else  1.5
            self._data.ctrl[ji.ctrl_index] = np.random.uniform(lo * 0.3, hi * 0.3)
        mujoco.mj_forward(self._model, self._data)
        self._target  = self._sample_target()
        self._step_n  = 0
        self._move_target_marker()
        return self._obs(), {}

    def step(self, action: np.ndarray):
        for i, ji in enumerate(self._ji):
            lo = ji.lower if not math.isinf(ji.lower) else -3.14159
            hi = ji.upper if not math.isinf(ji.upper) else  3.14159
            t  = lo + (float(action[i]) + 1.0) * 0.5 * (hi - lo)
            self._data.ctrl[ji.ctrl_index] = float(np.clip(t, lo, hi))

        for _ in range(5):     # 5 physics steps per RL step (= 20 ms)
            mujoco.mj_step(self._model, self._data)
        self._step_n += 1

        ee   = self._data.xpos[self._ee_id].astype(np.float32)
        dist = float(np.linalg.norm(ee - self._target))

        reached   = dist < 0.05
        reward    = -dist + (2.0 if reached else 0.0)
        terminated = reached
        truncated  = self._step_n >= self._max_steps

        return self._obs(), float(reward), terminated, truncated, {"dist": dist}

    def close(self):
        pass

    # Target as property (queried by RL panel for overlay)
    @property
    def target(self) -> np.ndarray:
        return self._target.copy()

    @property
    def ee_pos(self) -> np.ndarray:
        return self._data.xpos[self._ee_id].astype(np.float32)


# ── AMR environment ───────────────────────────────────────────────────────────

class MuJoCoAMREnv:
    """
    Point-to-point navigation for a differential-drive AMR.

    Observation (float32, shape = 7):
        dx, dy   — vector to goal in robot frame
        dist     — distance to goal
        sin(θ_err), cos(θ_err) — heading error
        v_left, v_right — current wheel velocities

    Action (float32, shape = 2, range [-1, 1]):
        Normalised left and right wheel velocity commands.

    Reward:
        -0.1 * dist_to_goal  +  3.0 when within 0.20 m of goal
        -0.5 if robot collides (contact force spike)
    """

    _MAX_SPEED = 3.0   # rad/s at action = 1.0
    _WHEEL_R   = 0.10  # metres
    _TRACK     = 0.25  # metres

    def __init__(self, mjcf_xml: str, joint_infos, max_steps: int = 500,
                 render_mode=None):
        if not GYM_AVAILABLE:
            raise ImportError("gymnasium is required for RL — pip install gymnasium")

        self._xml       = mjcf_xml
        self._wj        = [j for j in joint_infos if j.is_wheel]
        self._max_steps = max_steps
        self._step_n    = 0
        self._goal      = np.zeros(2, np.float32)

        self._model = mujoco.MjModel.from_xml_string(mjcf_xml)
        self._data  = mujoco.MjData(self._model)
        self._root_jid = mujoco.mj_name2id(
            self._model, mujoco.mjtObj.mjOBJ_JOINT, "root")

        self.observation_space = spaces.Box(-np.inf, np.inf, (7,), np.float32)
        self.action_space      = spaces.Box(-1.0, 1.0, (2,), np.float32)
        self.render_mode       = render_mode

    # ── internals ─────────────────────────────────────────────────────────────

    def _robot_pose(self):
        if self._root_jid < 0:
            return 0.0, 0.0, 0.0
        qadr = self._model.jnt_qposadr[self._root_jid]
        q    = self._data.qpos
        x, y = float(q[qadr]), float(q[qadr + 1])
        qw   = float(q[qadr + 3])
        qz   = float(q[qadr + 6])
        th   = 2.0 * math.atan2(qz, qw)
        return x, y, th

    def _obs(self) -> np.ndarray:
        x, y, th = self._robot_pose()
        gx, gy   = self._goal
        dx, dy   = gx - x, gy - y
        dist     = math.hypot(dx, dy)

        # rotate goal vector into robot frame
        c, s   = math.cos(-th), math.sin(-th)
        dx_r   = c * dx - s * dy
        dy_r   = s * dx + c * dy

        th_err = math.atan2(dy, dx) - th
        vl = float(self._data.ctrl[self._wj[0].ctrl_index]) if self._wj else 0.0
        vr = float(self._data.ctrl[self._wj[1].ctrl_index]) if len(self._wj) > 1 else 0.0

        return np.array([dx_r, dy_r, dist,
                         math.sin(th_err), math.cos(th_err),
                         vl / self._MAX_SPEED, vr / self._MAX_SPEED], np.float32)

    def _sample_goal(self) -> np.ndarray:
        angle = np.random.uniform(0, 2 * math.pi)
        r     = np.random.uniform(1.0, 3.5)
        return np.array([r * math.cos(angle), r * math.sin(angle)], np.float32)

    # ── Gymnasium API ─────────────────────────────────────────────────────────

    def reset(self, *, seed=None, options=None):
        if seed is not None:
            np.random.seed(seed)
        mujoco.mj_resetData(self._model, self._data)
        mujoco.mj_forward(self._model, self._data)
        self._goal   = self._sample_goal()
        self._step_n = 0
        return self._obs(), {}

    def step(self, action: np.ndarray):
        vl = float(np.clip(action[0], -1, 1)) * self._MAX_SPEED
        vr = float(np.clip(action[1], -1, 1)) * self._MAX_SPEED
        if self._wj:
            self._data.ctrl[self._wj[0].ctrl_index] = vl
        if len(self._wj) > 1:
            self._data.ctrl[self._wj[1].ctrl_index] = vr

        for _ in range(10):    # 10 × 4 ms = 40 ms per RL step
            mujoco.mj_step(self._model, self._data)
        self._step_n += 1

        x, y, _ = self._robot_pose()
        dist     = math.hypot(self._goal[0] - x, self._goal[1] - y)

        collide   = bool(self._data.ncon > 0 and
                         np.any(np.abs(self._data.cfrc_ext[:, 3:]) > 50.0))
        reached   = dist < 0.20
        reward    = -0.1 * dist + (3.0 if reached else 0.0) + (-0.5 if collide else 0.0)
        terminated = reached
        truncated  = self._step_n >= self._max_steps

        return self._obs(), float(reward), terminated, truncated,\
               {"dist": dist, "collide": collide}

    def close(self):
        pass

    @property
    def goal(self) -> np.ndarray:
        return self._goal.copy()
